# frozen_string_literal: true

source 'https://rubygems.org'
ruby '2.5.1'

gem 'activerecord'
gem 'byebug'
gem 'cucumber'
gem 'dotenv'
gem 'faker'
gem 'railties'
gem 'rspec'
gem 'rspec-rails'
gem 'json-schema'
